INSERT INTO `{#}content_datasets` (`ctype_id`, `name`, `title`, `ordering`, `is_visible`, `filters`, `sorting`, `groups_view`, `groups_hide`) VALUES
({id}, 'comments', 'Обсуждаемые', 3, 1, '0', '---\nby: comments\nto: desc\n', '---\n- 0\n', NULL),
({id}, 'rating', 'Популярные', 2, 1, '0', '---\nby: rating\nto: desc\n', '---\n- 0\n', NULL),
({id}, 'all', 'Все', 1, 1, '0', '---\nby: date_pub\nto: desc\n', '---\n- 0\n', NULL);

INSERT INTO `{#}perms_users` (`rule_id`, `group_id`, `subject`, `value`) VALUES
(1, 4, '{name}', '1'),
(1, 5, '{name}', '1'),
(1, 6, '{name}', '1'),
(4, 5, '{name}', '1'),
(4, 6, '{name}', '1'),
(3, 4, '{name}', 'own'),
(3, 5, '{name}', 'all'),
(3, 6, '{name}', 'all'),
(6, 5, '{name}', '1'),
(6, 6, '{name}', '1'),
(2, 4, '{name}', 'own'),
(2, 5, '{name}', 'all'),
(2, 6, '{name}', 'all'),
(5, 5, '{name}', '1'),
(5, 6, '{name}', '1'),
(9, 4, '{name}', '1'),
(9, 5, '{name}', '1'),
(9, 6, '{name}', '1'),
(8, 4, '{name}', '1'),
(8, 5, '{name}', '1'),
(8, 6, '{name}', '1'),
(13, 5, '{name}', '1'),
(13, 6, '{name}', '1');

CREATE TABLE `{#}con_{name}` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(100) DEFAULT NULL,
  `content` text,
  `slug` varchar(100) DEFAULT NULL,
  `seo_keys` text,
  `seo_desc` text,
  `tags` varchar(1000) DEFAULT NULL,
  `date_pub` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_last_modified` timestamp NULL DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `parent_id` int(11) DEFAULT NULL,
  `parent_type` varchar(32) DEFAULT NULL,
  `parent_title` varchar(100) DEFAULT NULL,
  `parent_url` varchar(255) DEFAULT NULL,
  `is_parent_hidden` tinyint(1) DEFAULT NULL,
  `category_id` int(11) NOT NULL DEFAULT '1',
  `folder_id` int(11) DEFAULT NULL,
  `is_comments_on` tinyint(1) DEFAULT NULL,
  `comments` int(11) NOT NULL DEFAULT '0',
  `rating` int(11) NOT NULL DEFAULT '0',
  `is_approved` tinyint(4) NOT NULL DEFAULT '1',
  `approved_by` int(11) DEFAULT NULL,
  `date_approved` timestamp NULL DEFAULT NULL,
  `is_private` tinyint(1) NOT NULL DEFAULT '0',
  `teaser` text,
  PRIMARY KEY (`id`),
  KEY `date_pub` (`date_pub`),
  KEY `user_id` (`user_id`),
  KEY `parent_id` (`parent_id`),
  KEY `parent_type` (`parent_type`),
  KEY `is_parent_hidden` (`is_parent_hidden`),
  KEY `category_id` (`category_id`),
  KEY `is_comments_on` (`is_comments_on`),
  KEY `comments` (`comments`),
  KEY `rating` (`rating`),
  KEY `is_approved` (`is_approved`),
  KEY `approved_by` (`approved_by`),
  KEY `date_approved` (`date_approved`),
  KEY `is_private` (`is_private`),
  KEY `folder_id` (`folder_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE `{#}con_{name}_cats` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `parent_id` int(11) DEFAULT NULL,
  `title` varchar(200) NOT NULL,
  `slug` varchar(255) DEFAULT NULL,
  `slug_key` varchar(255) DEFAULT NULL,
  `seo_keys` text,
  `seo_desc` text,
  `ordering` int(11) DEFAULT NULL,
  `ns_left` int(11) DEFAULT NULL,
  `ns_right` int(11) DEFAULT NULL,
  `ns_level` int(11) DEFAULT NULL,
  `ns_differ` varchar(32) NOT NULL DEFAULT '',
  `ns_ignore` tinyint(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `parent_id` (`parent_id`),
  KEY `ns_left` (`ns_left`),
  KEY `ns_right` (`ns_right`),
  KEY `ordering` (`ordering`),
  KEY `ns_differ` (`ns_differ`),
  KEY `ns_ignore` (`ns_ignore`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE `{#}con_{name}_fields` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ctype_id` int(11) DEFAULT NULL,
  `name` varchar(20) DEFAULT NULL,
  `title` varchar(100) DEFAULT NULL,
  `hint` varchar(200) DEFAULT NULL,
  `ordering` int(11) DEFAULT NULL,
  `fieldset` varchar(32) DEFAULT NULL,
  `type` varchar(16) DEFAULT NULL,
  `is_in_list` tinyint(1) DEFAULT NULL,
  `is_in_item` tinyint(1) DEFAULT NULL,
  `is_in_filter` tinyint(1) DEFAULT NULL,
  `is_private` tinyint(1) DEFAULT NULL,
  `is_fixed` tinyint(1) DEFAULT NULL,
  `is_fixed_type` tinyint(1) DEFAULT NULL,
  `is_system` tinyint(1) DEFAULT NULL,
  `values` text,
  `options` text,
  `groups_read` text,
  `groups_edit` text,
  PRIMARY KEY (`id`),
  KEY `ordering` (`ordering`),
  KEY `is_in_list` (`is_in_list`),
  KEY `is_in_item` (`is_in_item`),
  KEY `is_in_filter` (`is_in_filter`),
  KEY `is_private` (`is_private`),
  KEY `is_fixed` (`is_fixed`),
  KEY `is_fixed_type` (`is_fixed_type`),
  KEY `is_system` (`is_system`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE `{#}con_{name}_props` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ctype_id` int(11) DEFAULT NULL,
  `title` varchar(100) DEFAULT NULL,
  `fieldset` varchar(32) DEFAULT NULL,
  `type` varchar(16) DEFAULT NULL,
  `is_in_filter` tinyint(1) DEFAULT NULL,
  `values` text,
  `options` text,
  PRIMARY KEY (`id`),
  KEY `is_active` (`is_in_filter`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `{#}con_{name}_props_bind` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `prop_id` int(11) DEFAULT NULL,
  `cat_id` int(11) DEFAULT NULL,
  `ordering` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `prop_id` (`prop_id`),
  KEY `cat_id` (`cat_id`),
  KEY `ordering` (`ordering`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `{#}con_{name}_props_values` (
  `prop_id` int(11) DEFAULT NULL,
  `item_id` int(11) DEFAULT NULL,
  `value` varchar(255) DEFAULT NULL,
  KEY `prop_id` (`prop_id`),
  KEY `item_id` (`item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
